CRUD + AUTH de usuarios
MatiasOlivera/ypf-tienda pull request #18
Opened 2019-02-26 23:46 UTC by RomeoCirel

Esta rama agregar JWT AUTH, y el CRUD de los usuarios
Falta terminar el UsersController , UserUpdateRequest , entre

2019-02-27 02:19 UTC, MatiasOlivera commented
Agregar los pasos de instalación en el archivo `server/README.md`, incluyendo:

Generar la clave usada para firmar los tokens.  Es `JWT_SECRET` en `.env`. [Ver más](https://jwt-auth.readthedocs.io/en/develop/laravel-installation/)

    $ php artisan jwt:secret
    jwt-auth secret [IP2GXZsVMqB7rTiqz4HoX71elDLQOAZ4] set successfully

2019-02-27 03:19 UTC, MatiasOlivera requested changes

2019-02-27 03:19 UTC, MatiasOlivera commented on server/app/Http/Controllers/AuthController.php
> +
Debería haber un solo salto de línea. [Ver más](https://www.php-fig.org/psr/psr-2/#3-namespace-and-use-declarations)

2019-02-27 03:19 UTC, MatiasOlivera commented on server/app/Http/Controllers/AuthController.php
> +
No debería haber un salto de línea. [Ver más](https://www.php-fig.org/psr/psr-2/#43-methods)

2019-02-27 03:19 UTC, MatiasOlivera commented on server/app/Http/Controllers/AuthController.php
> +    protected function SetRespuestaToken($token)
El nombre del método debería escrito en camelCase: `setRespuestaToken`

2019-02-27 03:19 UTC, MatiasOlivera commented on server/app/User.php
> +    protected $table = 'cliente_usuario';
Por convención el nombre de la tabla es el nombre de la clase en plural, por lo que sería `clientes_usuarios`. [Ver más](https://laravel.com/docs/5.8/eloquent#eloquent-model-conventions)

2019-02-27 03:19 UTC, MatiasOlivera commented on server/composer.json
> +        "tymon/jwt-auth": "^1.0.0-rc.2"
Hay que commitear el archivo `composer.lock` cada vez que haya cambios. [Ver más](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control)

2019-02-27 03:19 UTC, MatiasOlivera commented on server/routes/api.php
> +Route::post('/usuarios/crear', 'UsersController@store')->name('RegistrarUsuario');
Para mantener la consistencia entre las rutas relacionadas con la autenticación:
1. La ruta podría ser `/auth/registro` 
2. El nombre de la ruta podría ser `registro`

2019-02-27 03:19 UTC, MatiasOlivera commented on server/routes/api.php
> +    Route::get('usuario', 'AuthController@usuario')->name('usuarioLogeado');
El nombre de la ruta podría ser `usuarioAutenticado`, me gusta más que usuario logueado

2019-02-27 04:01 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserCreateRequest.php
> +        $name = array([
🐛 **BUG**: La regla de validación `name` tiene una estructura incorrecta, por lo que no se valida el campo nombre provocando el error: `PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null`

```sh
# UserCreateRequest.php > rules()
{
  "email": [
    "bail",
    "required",
    "email",
    "max: 80",
    "unique:cliente_usuario,email"
  ],
  "password": ["bail", "required", "string", "min: 8", "confirmed"],
  "0": [{ "name": ["bail", "required", "string", "max: 50"] }]  # <-- Acá esta el problema
}
```

2019-02-27 04:24 UTC, MatiasOlivera requested changes

2019-02-27 04:24 UTC, MatiasOlivera commented on server/database/seeds/DatabaseSeeder.php
>          // $this->call(UsersTableSeeder::class);
Este comentario no se usa, podría borrarlo

2019-02-27 04:24 UTC, MatiasOlivera commented on server/database/seeds/UsuariosDev.php
> +class UsuariosDev extends Seeder
Deberíamos seguir una convensión para el nombre de las clases que generan los datos de prueba, algo como `TablaXSeeder`. En esta caso quedaría: `TablaUsuariosSeeder` [Ver más](https://laravel.com/docs/5.8/seeding#introduction)

2019-02-27 06:13 UTC, MatiasOlivera requested changes

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +
El salto de línea en linea 13 está de más

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +
El salto de línea en linea 77 está de más

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserCreateRequest.php
> +        $name = array([
🐛 **BUG**: La regla de validación `name` tiene una estructura incorrecta, por lo que no se valida el campo nombre provocando el error: `PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null`

```sh
# UserCreateRequest.php > rules()
{
  "email": [
    "bail",
    "required",
    "email",
    "max: 80",
    "unique:cliente_usuario,email"
  ],
  "password": ["bail", "required", "string", "min: 8", "confirmed"],
  "0": [{ "name": ["bail", "required", "string", "max: 50"] }]  # <-- Acá esta el problema
}
```

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $porPag = $request->input("porPag");
El acceso a los parámetros que se reciben en la `request` (línea 24) debería ser movido a la línea 21, para diferenciar más facilmente el input del resto del código.

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $campos = ['id', 'name', 'email', 'created_at'];
Faltan los campos `email_verified_at`, `id_cliente`, `updated_at` y `deleted_at`. Se deberían devolver todos los campos, porque no se sabe qué datos ni cómo los va a usar el cliente de la API. Saber si el email está verificado es útil a la hora de mostrar el estado de la cuenta en la interfaz. Ej: email verificado o esperando verificación

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $porPag = $request->input("porPag");
Creo que es mejor si evitamos las abreviaciones, a menos que la palabra sea excesivamente larga
```suggestion
        $porPagina = $request->input("porPagina ");
```

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $Users = new User();
Podrías simplificar este código:

```php
$Users = new User(); // 1
$lista = $Users::select($campos)->paginate($porPag);
$respuesta = $lista; // 2
return $respuesta;

// 1. No es necesario crear una instancia de User, porque el método select es estático
// 2. No es necesario asignar a otra variable
```

de esta forma:

```php
return User::select($campos)->paginate($porPag);
```

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +
El salto de línea en linea 48 está de más

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $User = new User();
El nombre de la instancia debería ser `$user` porque las instancias se escriben en minúsculas

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $respuesta = ['mensaje' => "El Usuario {$name} se creado con exito"];
Son solo errores de ortografía, deberíamos tratar de que no lleguen a producción ya que es texto que se muestra  al usuario.
```suggestion
            $respuesta = ['mensaje' => "El usuario {$name} se ha creado con éxito"];
```

2019-02-27 06:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +    public function Show($id)
Podrías simplificar este código:

```php
public function Show($id) // 1
{
    $user = User::findOrfail($id);
    return response()->json($user);
}

// 1.  El nombre del método debería estar en minúsculas
```

de esta forma:

```php
/**
 * Display the specified resource.
 *
 * @param App\User $User
 * @return \Illuminate\Http\Response
 */
public function show(User $user)
{
    return $user;
}
```

[Ver más](https://laravel.com/docs/5.7/routing#route-model-binding)

2019-02-27 06:13 UTC, MatiasOlivera commented on server/routes/api.php
> +        ->parameters(['usuario' => 'User']);
El nombre del parámetro de origen (`usuarios`) es igual que el nombre de la ruta (`/usuarios`). El alias debería ser escrito en minúsculas. 

> Cuando se modifique este archivo también debería modificarse el archivo  `UsersController.php`, cambiando los parámetros `$User` y `$usuario` por `$user` para mantener la consistencia.

```suggestion
        ->parameters(['usuarios' => 'user']);
```

2019-02-27 06:40 UTC, MatiasOlivera requested changes

2019-02-27 06:40 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +
El salto de línea en linea 99 está de más

2019-02-27 06:40 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +
El salto de línea en linea 108 está de más

2019-02-27 06:40 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $respuesta = ['mensaje' => "{ $name} ha sido actualizada"];
El espacio antes de la variable `$name` está de más
```suggestion
            $respuesta = ['mensaje' => "{$name} ha sido actualizado"];
```

2019-02-27 06:40 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $respuesta = ['mensaje' => "Hubo un problema al intentar actualizar a { $name}"];
Quitar el espacio antes de la variable `$name`

2019-02-27 06:40 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $eliminada = $User->delete();
Debería ser elminado, se esta hablando del usuario

2019-02-27 06:40 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $respuesta = ['mensaje' => "se elimino a {$nombre} con exito"];
```suggestion
            $respuesta = ['mensaje' => "Se eliminó a {$nombre} con éxito"];
```

2019-02-27 06:40 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $restaurada = $User->restore();
Lo mismo que arriba, debería ser restaurado

2019-02-27 06:40 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserUpdateRequest.php
> +// use Illuminate\Foundation\Http\FormRequest;
Evitar dejar código comentado, si no se va a usar es mejor eliminarlo. Lo mismo en las líneas 8, 15 y 16

2019-02-27 17:35 UTC, RomeoCirel commented on server/routes/api.php
> +Route::post('/usuarios/crear', 'UsersController@store')->name('RegistrarUsuario');
son dos cosas distintas:
**1.** Las rutas **/auth** son solo para el manejo de Sessiones (_en este caso Token_), login, renovarToken y logout.
**2.** La creacion de un usuario corresponde al CRUD Controller de Usuarios para lo cual el estandar indica la ruta **/usuarios/crear**.

2019-02-27 17:35 UTC, RomeoCirel commented on server/app/Http/Controllers/UsersController.php
> +        $campos = ['id', 'name', 'email', 'created_at'];
Esto no esta terminado faltan los filtros, paginado por defecto, etc era solo para tener algo andando

2019-02-27 17:35 UTC, RomeoCirel commented on server/app/Http/Requests/UsersRequest/UserUpdateRequest.php
> +// use Illuminate\Foundation\Http\FormRequest;
mas criterio a la hs de comentar estos comentarios no suman

2019-02-27 17:52 UTC, RomeoCirel commented on server/database/seeds/UsuariosDev.php
> +class UsuariosDev extends Seeder
En realidad seria **UserTableSeeder** para no buscar el nombre de la tabla en el medio, se lee mas rapido.
Pero en este caso no, es para generar solo nuestrso usuarios de prueba, los demas los hacemos con el factory, podria quedar **UsuariosDevelopeSeeder**.
A mi parecer generaria **ClienteUsuariosTablaSeeder** para generar los usuarios de produccion como el administrador o cosas asi.

2019-03-06 11:58 UTC, MatiasOlivera commented on server/routes/api.php
> +Route::post('/usuarios/crear', 'UsersController@store')->name('RegistrarUsuario');
Solucionado en 663f0e8e0c7d20d72f33c5c9817c172b54659dd0

2019-03-06 12:19 UTC, MatiasOlivera commented on server/database/seeds/UsuariosDev.php
> +class UsuariosDev extends Seeder
> En realidad seria UserTableSeeder para no buscar el nombre de la tabla en el medio, se lee mas rapido.

Deberíamos decidir si los nombres de los archivos van a estar en español o en inglés, solo para mantener la consistencia. En mi caso prefiero el español. Además, podriamos quitar directamente la palabra `Tabla`, para simplificar los nombres.

```
UserTableSeeder -> UsuarioSeeder
ClienteUsuariosTablaSeeder -> ClienteUsuariosSeeder
```

2019-03-06 12:48 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserCreateRequest.php
> +        $name = array([
Solucionado en 42c72835194f815a6804ebcea98af15b4c318254 ✔

2019-03-06 12:57 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserUpdateRequest.php
> +// use Illuminate\Foundation\Http\FormRequest;
Solucionado en 00957137f21fafed1df4bb435cfb793b89be5aa1 ✔

2019-03-06 14:05 UTC, MatiasOlivera requested changes
Actualmente, los nombres de los métodos que establecen las reglas de validación en los requests `UserCreateRequest` y `UserUpdateRequest` siguen la convención `SetCampoRequest()` pero estos métodos se encargan de definir las reglas dentro de un request, no son un request en sí.

Teniendo en cuenta lo anterior:

1. deberían seguir la siguiente convención `setReglaCampo()`
1. no creo que sea buena idea detallar cuál es la condición que se modifica
    - si se cambiaran las condiciones habría que cambiar el nombre del método
    - si las condiciones modificadas son muchas el nombre del método va a ser muy largo

Además, la primera letra del nombre del método debería estar en minúsculas.

```
SetNameRequest() -> setReglaName()
SetUniqueEmailRequest() -> setReglaEmail()
```

---

`UserCreateRequest`: Solucionado en 02091863cf2431a0ef16beeb8c4048add311eb31 ✔
`UserUpdateRequest`: Solucionado en 1fe246c422fa2076ab9bd83e9671c7da716951c9 ✔

2019-03-06 14:05 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserCreateRequest.php
> +        $this->reglas['name'] = $name;
No es necesario crear la variable `$name`, se puede asignar el arreglo directamente a `$this->reglas['name']`

```suggestion
        $this->reglas['name'] = ['bail', 'required', 'string', 'max:50'];
```

2019-03-06 14:40 UTC, MatiasOlivera commented on server/database/seeds/UsuariosDevelopeSeeder.php
> +class UsuariosDevelopeSeeder extends Seeder
Hay un typo en `Develope`, debería ser `Develop` sin la e. De todas maneras, si los nombres de los archivos van a ir en español deberíamos usar `UsuariosDesarrolloSeeder`. https://github.com/MatiasOlivera/ypf-tienda/pull/18#discussion_r262916355

2019-03-06 14:40 UTC, MatiasOlivera commented on server/app/User.php
> +    protected $table = 'cliente_usuario';
Solucionado en 7a44a6873221fa2e29621bf3fb87eacd51ba92e2 ✔

2019-03-06 14:58 UTC, MatiasOlivera commented on server/app/Http/Controllers/AuthController.php
> +
Solucionado en bfa5a6c5d7904a46cf8b5654603154d7d94a14a3 ✔

2019-03-06 15:00 UTC, MatiasOlivera commented on server/app/Http/Controllers/AuthController.php
> +    protected function SetRespuestaToken($token)
Solucionado en bfa5a6c5d7904a46cf8b5654603154d7d94a14a3 ✔

2019-03-06 15:10 UTC, MatiasOlivera commented on server/routes/api.php
> +    Route::get('usuario', 'AuthController@usuario')->name('usuarioLogeado');
Solucionado en 663f0e8e0c7d20d72f33c5c9817c172b54659dd0 ✔

2019-03-06 15:10 UTC, MatiasOlivera commented on server/routes/api.php
> +        ->parameters(['usuario' => 'User']);
Solucionado en 663f0e8e0c7d20d72f33c5c9817c172b54659dd0 ✔

2019-03-06 15:19 UTC, MatiasOlivera requested changes

2019-03-06 15:19 UTC, MatiasOlivera commented on server/routes/api.php
> +    Route::POST('/usuarios/{user}/restaurar/', 'UsersController@restore')->name('usuarios.restore');
El método debería estar en minúsculas y no es necesario especificar el nombre de la ruta ya que se va a usar.

```suggestion
    Route::post('/usuarios/{user}/restaurar/', 'UsersController@restore')
```

2019-03-06 15:19 UTC, MatiasOlivera commented on server/database/seeds/UsuariosDevelopeSeeder.php
> +class UsuariosDevelopeSeeder extends Seeder
Hay un typo en `Develope`, debería ser `Develop` sin la e. De todas maneras, si los nombres de los archivos van a ir en español deberíamos usar `UsuariosDesarrolloSeeder`. https://github.com/MatiasOlivera/ypf-tienda/pull/18#discussion_r262916355

2019-03-06 15:21 UTC, MatiasOlivera commented on server/composer.json
> +        "tymon/jwt-auth": "^1.0.0-rc.2"
Solucionado en aa76201761c56312465a30d61ecd2cbe78412a30 ✔

2019-03-06 15:23 UTC, MatiasOlivera requested changes

2019-03-06 15:23 UTC, MatiasOlivera commented on server/app/Cliente.php
> +    protected $fillable = ['dni', 'cliente', 'obsevacion', ];
Hay un typo en `obsevacion`, debería ser `observacion`

2019-03-06 22:20 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $porPag = $request->input("porPag");
Solucionado en 43799df8d31d0cd73aa7b0a122c103e7fd0eaacc ✔

2019-03-06 22:58 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $campos     = ['id', 'name', 'email', 'email_verified_at', 'id_cliente', 'created_at', 'updated_at', 'deleted_at',];
Los campos son las columnas en donde se realiza la búsqueda, en este caso serían name y email.

2019-03-06 22:58 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $User = new User();
Solucionado en 43799df8d31d0cd73aa7b0a122c103e7fd0eaacc ✔

2019-03-06 22:59 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +    public function Show($id)
Solucionado en  43799df8d31d0cd73aa7b0a122c103e7fd0eaacc ✔

2019-03-06 23:00 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $respuesta = ['mensaje' => "{ $name} ha sido actualizada"];
Solucionado en 43799df8d31d0cd73aa7b0a122c103e7fd0eaacc ✔

2019-03-06 23:32 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $Users = new User();
Solucionado en 43799df8d31d0cd73aa7b0a122c103e7fd0eaacc ✔

2019-03-06 23:45 UTC, MatiasOlivera commented on server/app/Cliente.php
> +    protected $fillable = ['dni', 'cliente', 'obsevacion', ];
Obsevacion es el nombre de la columna en la tabla. Se va a arreglar más adelante.

2019-03-07 00:22 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $campos = ['id', 'name', 'email', 'created_at'];
Solucionado en 43799df8d31d0cd73aa7b0a122c103e7fd0eaacc ✔

2019-03-07 02:46 UTC, MatiasOlivera requested changes

2019-03-07 02:46 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserUpdateRequest.php
> +    private function SetEmailRequest()
Los métodos deberían seguir la siguiente convención `setReglaCampo()`. https://github.com/MatiasOlivera/ypf-tienda/pull/18#pullrequestreview-211230688

2019-03-13 13:16 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserUpdateRequest.php
> +    private function SetEmailRequest()
Solucionado en 1fe246c422fa2076ab9bd83e9671c7da716951c9 ✔

2019-03-13 14:41 UTC, MatiasOlivera requested changes

2019-03-13 14:41 UTC, MatiasOlivera commented on server/app/Auxiliares/Consulta.php
> +    public function setOrndenarPor($string)
Hay un typo en ordenar

2019-03-13 14:55 UTC, MatiasOlivera requested changes

2019-03-13 14:55 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +        $metodo   = new BaseController;
La variable `$método` debería llamarse `$controlador` porque es una instancia de `BaseController`

2019-03-14 00:12 UTC, MatiasOlivera commented on server/database/seeds/DatabaseSeeder.php
>          // $this->call(UsersTableSeeder::class);
Solucionado en 78c15191cedf9cb693845c39b7103b481a27a563 ✔

2019-03-14 00:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $respuesta = ['mensaje' => "El Usuario {$name} se creado con exito"];
Solucionado en 78c15191cedf9cb693845c39b7103b481a27a563 ✔

2019-03-14 00:13 UTC, MatiasOlivera commented on server/app/Http/Controllers/UsersController.php
> +            $respuesta = ['mensaje' => "se elimino a {$nombre} con exito"];
Solucionado en 78c15191cedf9cb693845c39b7103b481a27a563 ✔

2019-03-14 00:13 UTC, MatiasOlivera commented on server/app/Http/Requests/UsersRequest/UserCreateRequest.php
> +        $this->reglas['name'] = $name;
Solucionado en 78c15191cedf9cb693845c39b7103b481a27a563 ✔

2019-03-14 00:13 UTC, MatiasOlivera commented on server/routes/api.php
> +    Route::POST('/usuarios/{user}/restaurar/', 'UsersController@restore')->name('usuarios.restore');
Solucionado en 78c15191cedf9cb693845c39b7103b481a27a563 ✔

2019-03-14 00:14 UTC, MatiasOlivera commented on server/database/seeds/UsuariosDevelopeSeeder.php
> +class UsuariosDevelopeSeeder extends Seeder
Solucionado en 78c15191cedf9cb693845c39b7103b481a27a563 ✔

2019-03-14 00:14 UTC, MatiasOlivera commented on server/app/Auxiliares/Consulta.php
> +    public function setOrndenarPor($string)
Solucionado en 78c15191cedf9cb693845c39b7103b481a27a563 ✔

2019-03-14 00:30 UTC, MatiasOlivera approved these changes

2019-03-14 00:33 UTC, merged